# ============================================
# Configuración del servidor
# ============================================
server.port=8080

# ============================================
# Conexión a PostgreSQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/servicio_tecnico_domicilio
spring.datasource.username=postgres
spring.datasource.password=Aeiou12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / Hibernate
# ============================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# Multipart (para subida de imágenes más adelante)
# ============================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ============================================
# JWT
# ============================================
jwt.secret=Zn4vK8mQ2xL7wP9dR3hF6sJ0cY5bT8gA1oU4eN6kM3xW7pQ
jwt.expiration=86400000

# ============================================
# Correo (Gmail SMTP)
# ============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shadowanonymoususer01@gmail.com
spring.mail.password=cbenwjcozrthwgwv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true